# action.yaml
name: "PyInstaller Linux"
description: "Customisable GitHub Action to package your python code with PyInstaller for Linux"
branding:
  icon: "box"
  color: "blue"
inputs:
  path:
    description: "Directory containing source code & .spec file (optional requirements.txt)."
    required: True
    default: src
  pypi_url:
    description: "Specify a custom URL for PYPI"
    required: False
    default: https://pypi.python.org/
  pypi_index_url:
    description: "Specify a custom URL for PYPI Index"
    required: False
    default: https://pypi.python.org/simple
  spec:
    description: "Specify a file path for .spec file"
    required: False
    default: ""
  tkinter:
    description: "Specify whether to install Tkinter or not"
    required: False
    default: "false"
  requirements:
    description: 'Specify a file path for requirements.txt file'
    required: False
    default: "requirements.txt"
  gooey:
    description: "Specify whether to install Gooey or not"
    required: False
    default: "true"
outputs:
  output:
    description: "The output of PyInstaller"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}            #$1
    - ${{ inputs.pypi_url }}        #$2
    - ${{ inputs.pypi_index_url }}  #$3
    - ${{ inputs.spec }}            #$4
    - ${{ inputs.tkinter }}         #$5
    - ${{ inputs.requirements }}    #$6
    - ${{ inputs.gooey }}           #$7
